# setup our base image 

FROM node:16-alpine

# setup working directory 

WORKDIR /app

# copy over our package.json file to root

COPY package.json ./

RUN npm install 

COPY ./ ./

CMD ["npm", "start"]